server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meetingroom
    username: root
    password: 123456
#logging:
#  # 设置logback.xml位置
#  #  config: classpath:log/logback.xml
#  # 设置log4j.properties位置
#  config: classpath:log4j.properties

jwt:
  header: Authorization
  base64-secret: meng
  token-validity-in-seconds: 14400000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type=auto: